#!/bin/sh
set -e

. /usr/share/debconf/confmodule

file="$1"

cat > $file << EOF
#TITLE: Sitio principal de Guadalinex en la Junta de Andalucia
#ID:jda
deb http://v6.guadalinex.org/ubuntu jaunty main restricted universe multiverse
deb http://v6.guadalinex.org/guadalinex-buho buho main restricted universe multiverse
deb http://v6.guadalinex.org/guadalinex-buho buho-updates main restricted universe multiverse
deb http://v6.guadalinex.org/guadalinex-buho buho-security main restricted universe multiverse
deb http://v6.guadalinex.org/guadalinex-buho buho-backports main restricted universe multiverse
#END
EOF

