#!/bin/sh

set -e

#DEBHELPER#

dpkg-divert --package guada-ubiquity --add --rename \
         --divert /usr/lib/ubiquity/ubiquity/frontend/__init__.py.real /usr/lib/ubiquity/ubiquity/frontend/__init__.py
ln -fs /usr/lib/guada-ubiquity/ubiquity/frontend/__init__.py /usr/lib/ubiquity/ubiquity/frontend/__init__.py

echo "X_LOADTEMPLATEFILE /usr/share/guada-ubiquity/templates/ubiquity.templates" | debconf-communicate
