#!/bin/bash
#set -x
DERIVATIVE_PACKAGES=/var/gensys/deb-repositories/gv6
DERIVATIVE_REPOSITORY=/var/gensys/deb-repositories/derivative-repo
REPREPRO=/usr/bin/reprepro
LOG_FILE=/var/gensys/update-derivative.log
CODENAME=buho
OPTIONS="-Vb $DERIVATIVE_REPOSITORY --ignore=wrongdistribution"

# Ready...
# Including packages
for pkg in $(ls $DERIVATIVE_PACKAGES | grep -E '.*deb$|.*dsc$');do
  if [[ $(echo $pkg|awk -F . '{print $NF}') = "dsc" ]];then
	$REPREPRO $OPTIONS -S guada -P low includedsc $CODENAME $DERIVATIVE_PACKAGES/$pkg | tee -a $LOG_FILE
  else	
	if [[ $(echo $pkg|awk -F . '{print $NF}') = "udeb" ]];then
  		$REPREPRO $OPTIONS includeudeb $CODENAME $DERIVATIVE_PACKAGES/$pkg | tee -a $LOG_FILE
  	else
        	$REPREPRO $OPTIONS includedeb $CODENAME $DERIVATIVE_PACKAGES/$pkg | tee -a $LOG_FILE
	fi
  fi
done

chmod 755 -R $DERIVATIVE_REPOSITORY
