#!/bin/sh

if [ "$1" = "configure" ]; then
	if dpkg --compare-versions "$2" lt-nl "0.97-29ubuntu6"; then
		update-grub
	fi
	# This is an old misnamed config file we need to get rid of
	rm -f /etc/event.d/event.d-last-good-boot
fi

if [ "x$1" = xtriggered ] ; then
	/usr/sbin/update-grub
fi

if [ "$1" = "configure" ]; then
	# Create a last-good-boot if one doesn't exist.
	/usr/sbin/kernel-helper -i
fi

#DEBHELPER#
