# Generic and common files
common/C/*xml usr/share/ubuntu-docs/common/C
common/authors/* usr/share/ubuntu-docs/common/authors
libs/*ent usr/share/ubuntu-docs/libs
libs/xinclude.mod usr/share/ubuntu-docs/libs
ubuntu/libs/*ent usr/share/gnome/help/libs
ubuntu/libs/*ent usr/share/ubuntu-docs/ubuntu/libs
generic/libs/*ent usr/share/ubuntu-docs/ubuntu/libs
generic/libs/*ent usr/share/gnome/help/libs
libs/* usr/share/gnome/libs
libs/* usr/share/gnome/help/libs
libs/* usr/share/ubuntu-docs/libs
ubuntu/libs/*ent usr/share/gnome/help/libs
ubuntu/libs/*ent usr/share/ubuntu-docs/libs

# Server Guide - Sample files
generic/serverguide/sample/* usr/share/ubuntu-docs/ubuntu/sample

# Firefox start page
ubuntu/browser-startpage/index.html usr/share/ubuntu-artwork/home
ubuntu/browser-startpage/ubuntu.css usr/share/ubuntu-artwork
ubuntu/browser-startpage/img/* usr/share/ubuntu-artwork/img
ubuntu/libs/img/ubuntuheader.png usr/share/ubuntu-docs/help/images/C
ubuntu/libs/img/ubuntuheader.png usr/share/gnome/help/images/C/

#Firefox start page translations
ubuntu/browser-startpage/index-lt.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-sk.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-zh_CN.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-pl_PL.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-es.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-sv_SE.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-fi_FI.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-ru_RU.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-cs_CZ.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-it_IT.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-pt_BR.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-hu_HU.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-fr.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-nl.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-de.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-bn.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-ar.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-he_IL.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-ku.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-da.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-zh_TW.html usr/share/ubuntu-artwork/home/locales-ubuntu
ubuntu/browser-startpage/index-ka_GE.html usr/share/ubuntu-artwork/home/locales-ubuntu
