#!/bin/bash

cd /usr/share/gnome/help/
for app in $(ls -1); do
    cd $app
    for lang in $(ls -1); do
       if [ "$lang" != "C" ] && [ "$lang" != "es" ]; then
           rm -fr $lang
       fi
    done
    cd /usr/share/gnome/help/
done
